# Variables

In [2]:
y = 5

In [3]:
type(y)

int

In [4]:
y = 2.5

In [5]:
type(y)

float

In [8]:
y = "hello"

In [9]:
type(y)

str

In [10]:
y = True

In [11]:
type(y)

bool

---

# Simple Math

In [13]:
import math

In [14]:
math.sqrt(4)

2.0

In [16]:
a = "welcome"
b = " to hell"
a+b

'welcome to hell'

---

# Simple Arithmatic

In [20]:
4<5

True

In [21]:
# and
# or
# not
# != < == >

In [22]:
result = not(5>1)
result

False

---

# While Loop

In [26]:
counter = 0
while counter < 12:
    print(counter)
    counter = counter + 1

0
1
2
3
4
5
6
7
8
9
10
11


---

# For Loop

In [30]:
list(range(5))

[0, 1, 2, 3, 4]

In [35]:
counter = 0
li = ["first","second","third","fourth","fifth"]
for i in range(5):
    print("hi ",i," how ", i)
    print("iteration",li[i])

hi  0  how  0
iteration first
hi  1  how  1
iteration second
hi  2  how  2
iteration third
hi  3  how  3
iteration fourth
hi  4  how  4
iteration fifth


---

# If Condition

In [37]:
import numpy as np
from numpy.random import randn

In [104]:
x = randn()
answer = None
if(x>1):
    answer = "it is greater than 1"
else:
    if(x<-1):
        answer = "it is less than -1"
    else:
        answer = "it is between"
print(x)
print(answer)

-1.3236563368222565
it is less than -1


In [114]:
x = randn()
answer = None
if(x>1):
    answer = "it is greater than 1"
elif(x<-1):
    answer = "it is less than -1"
else:
    answer = "it is between"
print(x)
print(answer)

1.8105896655943303
it is greater than 1


---

# Testing Normal Distribution

In [127]:
x = []
sum_bet = 0
numbers = 10000
for i in range(numbers):
    x.append(randn())
    if x[i] > -1 and x[i] < 1:
        sum_bet = sum_bet + 1
pr = sum_bet/numbers
pr

0.6798

In [128]:
x = []
sum_bet = 0
numbers = 10000
for i in randn(numbers):
    x.append(i)
    if i > -1 and i < 1:
        sum_bet = sum_bet + 1
pr = sum_bet/numbers
pr

0.6815

---

# Lists

In [132]:
x = list(range(100,90,-1))
x

[100, 99, 98, 97, 96, 95, 94, 93, 92, 91]

In [136]:
letters = ["a","b","c","d","e","f","g","h","i","j","k","l"]
letters[-2]

'k'

In [142]:
print(letters[::-3])

['l', 'i', 'f', 'c']


In [143]:
type(letters)

list

---

# Tuples

In [140]:
tup = (1,2,3)

In [141]:
tup[0] = 3

TypeError: 'tuple' object does not support item assignment

In [144]:
type(tup)

tuple

In [145]:
min(tup)

1

In [146]:
max(tup)

3

---

# Arrays

In [155]:
a = letters.copy()
a

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l']

In [158]:
b = np.array(a)
b

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'],
      dtype='<U1')

---

# Simple Analysis

In [159]:
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [161]:
len(expenses)

12

In [200]:
profit = [round(i-j,2) for i,j in zip(revenue,expenses)]
profit

[2522.67,
 1911.39,
 -3707.79,
 -2914.31,
 -599.92,
 7265.24,
 8210.55,
 3944.97,
 3328.39,
 -2238.65,
 659.6,
 11629.54]

In [204]:
prof = []
for i in range(len(revenue)):
    prof.append(round(revenue[i]-expenses[i],2))
prof

[2522.67,
 1911.39,
 -3707.79,
 -2914.31,
 -599.92,
 7265.24,
 8210.55,
 3944.97,
 3328.39,
 -2238.65,
 659.6,
 11629.54]

In [206]:
prof_after_tax = [round((i*7)/10,2) for i in prof]
print(prof_after_tax)

[1765.87, 1337.97, -2595.45, -2040.02, -419.94, 5085.67, 5747.38, 2761.48, 2329.87, -1567.06, 461.72, 8140.68]


In [207]:
prof_margin = [round(i/j,2) for i,j in zip(prof_after_tax,revenue)]
prof_margin

[0.12, 0.18, -0.3, -0.22, -0.05, 0.63, 0.5, 0.28, 0.23, -0.11, 0.04, 0.53]

In [209]:
good_months = [0]*12
mean_year = round(sum(prof_after_tax)/len(prof_after_tax),2)
print("mean: ",mean_year)
counter = 0
for i in prof_after_tax:
    if i > mean_year:
        good_months[counter] = i
        print(counter)
    counter = counter + 1

mean:  1750.68
0
5
6
7
8
11


In [210]:
bad_months = [0]*12
mean_year = round(sum(prof_after_tax)/len(prof_after_tax),2)
print("mean: ",mean_year)
counter = 0
for i in prof_after_tax:
    if i < mean_year:
        bad_months[counter] = i
        print(counter)
    counter = counter + 1

mean:  1750.68
1
2
3
4
9
10


In [195]:
best_months = max(prof_after_tax)
counter = 0
for i in prof_after_tax:
    if i == best_months:
        print(counter)
    counter = counter + 1

11


In [197]:
worst_months = min(prof_after_tax)
counter = 0
for i in prof_after_tax:
    if i == worst_months:
        print(counter)
    counter = counter + 1

2


---

# Simple Analysis 2

In [211]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [212]:
#Solution
#Calculate Profit As The Differences Between Revenue And Expenses
profit = []

for i in range (0, len(revenue)):
    profit.append(revenue[i] - expenses [i])
profit

[2522.67,
 1911.3900000000003,
 -3707.790000000001,
 -2914.3099999999995,
 -599.9200000000001,
 7265.24,
 8210.550000000001,
 3944.9700000000003,
 3328.3899999999994,
 -2238.6500000000015,
 659.5999999999985,
 11629.54]

In [213]:
#Calculate Tax As 30% Of Profit And Round To 2 Decimal Points
tax = [round(i * 0.3, 2) for i in profit]
tax



[756.8,
 573.42,
 -1112.34,
 -874.29,
 -179.98,
 2179.57,
 2463.17,
 1183.49,
 998.52,
 -671.6,
 197.88,
 3488.86]

In [214]:
#Calculate Profit Remaining After Tax Is Deducted
profit_after_tax = []
for i in range (0, len(profit)):
    profit_after_tax.append(profit[i] - tax[i])
profit_after_tax

[1765.8700000000001,
 1337.9700000000003,
 -2595.4500000000007,
 -2040.0199999999995,
 -419.94000000000005,
 5085.67,
 5747.380000000001,
 2761.4800000000005,
 2329.8699999999994,
 -1567.0500000000015,
 461.71999999999855,
 8140.68]

In [215]:
#Calculate The Profit Margin As Profit After Tax Over Revenue
#Round To 2 Decimal Points, Then Multiply By 100 To Get %
profit_margin = []
for i in range (0, len(profit)):
    profit_margin.append(profit_after_tax[i] / revenue[i])
profit_margin

profit_margin = [round(i*100,2) for i in profit_margin]

profit_margin

[12.12,
 17.59,
 -30.14,
 -22.23,
 -5.21,
 62.74,
 49.99,
 28.28,
 22.61,
 -10.9,
 4.31,
 52.75]

In [216]:
#Calculate The Mean Profit After Tax For The 12 Months
mean_pat = sum(profit_after_tax) / len(profit)
mean_pat

1750.6816666666666

In [217]:
#Find The Months With Above-Mean Profit After Tax
good_months = []
for i in range (0, len(profit)):
    good_months.append(profit_after_tax[i] > mean_pat)
good_months

[True, False, False, False, False, True, True, True, True, False, False, True]

In [218]:
#Bad Months Are The Opposite Of Good Months!
bad_months = []
for i in range (0, len(profit)):
    bad_months.append(not (good_months[i]))
bad_months

[False, True, True, True, True, False, False, False, False, True, True, False]

In [219]:
#The Best Month Is Where Profit After Tax Was Equal To The Maximum
best_month = []
for i in range (0, len(profit)):
    best_month.append(profit_after_tax[i] == max(profit_after_tax))
best_month

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True]

In [220]:
#The Worst Month Is Where Profit After Tax Was Equal To The Minimum
worst_month = []
for i in range (0, len(profit)):
    worst_month.append(profit_after_tax[i] == min(profit_after_tax))
worst_month

[False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [222]:
#Convert All Calculations To Units Of One Thousand Dollars
revenue_1000 = [round(i/1000, 2) for i in revenue]
expenses_1000 = [round(i/1000, 2) for i in expenses]
profit_1000 = [round(i/1000, 2) for i in profit]
profit_after_tax_1000 = [round(i/1000, 2) for i in profit_after_tax]

revenue_1000 = [int(i) for i in revenue_1000]
expenses_1000 = [int(i) for i in expenses_1000]
profit_1000 = [int(i) for i in profit_1000]
profit_after_tax_1000 = [int(i) for i in profit_after_tax_1000]

In [223]:
#Print Results
print ("Revenue :") 
print (revenue_1000)
print ("Expenses :") 
print (expenses_1000)
print ("Profit :")
print(profit_1000)
print ("Profit after tax :")
print (profit_after_tax_1000)
print ("Profit margin :")
print (profit_margin)
print ("Good months :")
print (good_months)
print ("Bad months :")
print (bad_months)
print ("Best month :")
print (best_month)
print ("Worst month :")
print (worst_month)

Revenue :
[14, 7, 8, 9, 8, 8, 11, 9, 10, 14, 10, 15]
Expenses :
[12, 5, 12, 12, 8, 0, 3, 5, 6, 16, 10, 3]
Profit :
[2, 1, -3, -2, 0, 7, 8, 3, 3, -2, 0, 11]
Profit after tax :
[1, 1, -2, -2, 0, 5, 5, 2, 2, -1, 0, 8]
Profit margin :
[12.12, 17.59, -30.14, -22.23, -5.21, 62.74, 49.99, 28.28, 22.61, -10.9, 4.31, 52.75]
Good months :
[True, False, False, False, False, True, True, True, True, False, False, True]
Bad months :
[False, True, True, True, True, False, False, False, False, True, True, False]
Best month :
[False, False, False, False, False, False, False, False, False, False, False, True]
Worst month :
[False, False, True, False, False, False, False, False, False, False, False, False]


---

# Dictionaries

In [16]:
dic1 = {'key1':'val1','key2':2,'key3':True}
dic1['key2']

2

---

# Reshaping

In [8]:
my_data = np.arange(0,20)
print(my_data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
np.reshape(my_data,(5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
np.reshape(my_data,(5,4),order = "F")

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [13]:
my_data.reshape((5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])